import { Bebas_Neue, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
});
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
